# -*- coding: utf-8 -*-
"""phython_intermeduate5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0_uEDm8exe5REn35Bem7vsagj1xwEMp
"""

#strings: ordered, immutable, text representation
my_string = "I'm a programmer"
print(my_string)

my_string2 = """Hello
World"""
print(my_string2)

my_string = "Hello World"
char = my_string[0]
print(char)
substring = my_string[1:5]
print(substring)

greeting = "Hello"
name = "Tom"
sentence = greeting + " " + name
print(sentence)

greeting = "Hello"
for i in greeting:
  print(i)

if 'e' in greeting:
  print('Yes')
else:
  print('No')

my_string = '   Hello World   '
my_string = my_string.strip()
print(my_string)

my_string = 'Hello World'
print(my_string.upper())
print(my_string.startswith('H'))
print(my_string.endswith('World'))
print(my_string.find('o'))
print(my_string.count('l'))

my_string = 'Hello World'
print(my_string.replace('World', 'Universe'))

my_string = 'how are you doing'
my_list = my_string.split(" ")
print(my_list)
new_string = ' '.join(my_list)
print(new_string)

my_list = ['a'] * 6
print(my_list)

#bad
my_string = ''
for i in my_list:
  my_string += i
print(my_string)

#good
my_string = ''.join(my_list)
print(my_string)

# %, .fomart(), f-Strings
var = "Tom"
my_string = "the variable is %s" % var
print(my_string)

var = 3
my_string2 = "the variable is %d" % var
print(my_string2)

var = 3.111223
my_string3 = "the variable is %f" % var
print(my_string3)

var = 3.1112223
var2 = 6
my_string = "the variable is {:.2f} and {}".format(var,var2)
print(my_string)

var = 3.1112223
var2 = 6
my_string = f"the variable is {var} and {var2}"
print(my_string)