# -*- coding: utf-8 -*-
"""phython_intermediate_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPUakyVKuOhrFvcgkMUBJ9BBuOVv-f7X
"""

#Lists: ordered, mutable, allows duplicate elements
mylist = ["banana", "cherry", "apple"]

for x in mylist:
  print(x)

if "apple" in mylist:
  print("yes")

else:
  print("no")

print(len(mylist))

mylist.append("lemon")
print(mylist)

mylist.insert(1, "blueberry")
print(mylist)

item = mylist.pop()
print(item)
print(mylist)

item2 = mylist.remove("cherry")
print(mylist)

item3 = mylist.reverse()
print(mylist)

mylist2 = [1, 2, 3, -1, -2, -3]
a = mylist2[1:4]
print(a)
print(mylist2)

new_list = sorted(mylist2)
print(mylist2)
print(new_list)

mylist3 = [0] * 5
print(mylist3)

new_list2 = mylist2 + mylist3
print(new_list2)

list_org = ["banana", "cherry", "apple"]

list_cpy = list_org[:]

list_cpy.append("lemon")

print(list_cpy)
print(list_org)

mylist = [1, 2, 3, 4, 5, 6]
b = [i*i for i in mylist]

print(mylist)
print(b)