# -*- coding: utf-8 -*-
"""phython_intermediate4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_ztG3kxDoa6Tw9_P1Ju6R5qc8JgpSgJ
"""

#Sets: unordered, mutable, no duplicates
myset = {1, 2, 3, 1, 2}
print(myset)

myset = set([1, 2, 3])
print(myset)

myset = set("Hello")
print(myset)

myset = set()
print(type(myset))

myset = set()

myset.add(1)
myset.add(2)
myset.add(3)

myset.remove(3)
myset.discard(2)
myset.discard(4)
print(myset)

myset = set()

myset.add(1)
myset.add(2)

myset.clear()

print(myset)

myset = set()

myset.add(1)
myset.add(2)
myset.add(3)

print(myset.pop())

print(myset)

myset = set()

myset.add(1)
myset.add(2)

for x in myset:
  print(x)

if 1 in myset:
  print("yes")

odds = {1, 3, 5, 7, 9}
evens = {0, 2, 4, 6, 8}
primes = {2, 3, 5, 7}

u = odds.union(evens)
print(u)

i = odds.intersection(evens)
print(i)

setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}

diff = setA.difference(setB)
print(diff)

diff2 = setB.symmetric_difference(setA)
print(diff2)

setA.update(setB)
print(setA)

setA.intersection_update(setB)
print(setA)

setA = {1, 2, 3, 4, 5, 6}
setB = {1, 2, 3}
setC = {7, 8}

print(setA.issubset(setB))
print(setA.issuperset(setB))
print(setA.isdisjoint(setC))

setA = {1, 2, 3, 4, 5, 6}

setB = setA.copy()

setB.add(7)
print(setB)
print(setA)

a = frozenset([1, 2, 3, 4])

print(a)